### ISSUE TITLE
MakeAnimation always returns nil value

### ISSUE THREAD

**Issue by misnaged** [cebarks/spriteplus#2]
Hi there! I got stucked with MakeAnimation func as it is always returning nil value.

I've tried to make some really simple and basic thing like this:

```
       p1, _ := loadPicture("01.png")
	p2, _ := loadPicture("02.png")
	sprite1 :=  pixel.NewSprite(p1, p1.Bounds())
	sprite2 :=  pixel.NewSprite(p2, p2.Bounds())

	var Sprites []*pixel.Sprite

	Sprites = append(Sprites, sprite1, sprite2)

	anim, _ := spriteplus.MakeAnimation(Sprites, 2)
	fmt.Println("debug output is:", anim)
	anim.Draw(win, pixel.IM.Moved(win.Bounds().Center()))

```
	
`debug output is: <nil>`

=(

**Comment by cebarks** [comment]
What's the value of the error being returned from MakeAnimation? My guess is your two sprites aren't the same size so its failing the internal check being done.

**Comment by misnaged** [comment]
It starts to panic. So it occurs at runtime

**Comment by misnaged** [comment]
```
debug output is: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x51a797]

```

**Comment by cebarks** [comment]
It's panicing because `anim` is set to `nil`. If anim is nil, that means you're getting an error from `spriteplus.MakeAnimation()`. Currently, the only way that function will return an error is if the size of the sprites used don't match.

**Comment by misnaged** [comment]
Yep! You were absolutely right about the size =D
